// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREh73osQK14GtAP3Y5x12TwJqk1Ybkxs',
    appId: '1:484006019055:web:879f1b0c4afe5fd2eb801a',
    messagingSenderId: '484006019055',
    projectId: 'activity16-93cc8',
    authDomain: 'activity16-93cc8.firebaseapp.com',
    storageBucket: 'activity16-93cc8.firebasestorage.app',
    measurementId: 'G-WHWS2P6GTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRkI4WWH7MAmonSePFsk6ezjTW8yUpXoQ',
    appId: '1:484006019055:android:efdebe6fa0905142eb801a',
    messagingSenderId: '484006019055',
    projectId: 'activity16-93cc8',
    storageBucket: 'activity16-93cc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpS3HILclEDlXg2H2npem0v4vH7brLwU',
    appId: '1:484006019055:ios:a39ead6cebf18455eb801a',
    messagingSenderId: '484006019055',
    projectId: 'activity16-93cc8',
    storageBucket: 'activity16-93cc8.firebasestorage.app',
    iosBundleId: 'com.example.signupAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpS3HILclEDlXg2H2npem0v4vH7brLwU',
    appId: '1:484006019055:ios:a39ead6cebf18455eb801a',
    messagingSenderId: '484006019055',
    projectId: 'activity16-93cc8',
    storageBucket: 'activity16-93cc8.firebasestorage.app',
    iosBundleId: 'com.example.signupAdventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBREh73osQK14GtAP3Y5x12TwJqk1Ybkxs',
    appId: '1:484006019055:web:735026e4397972fbeb801a',
    messagingSenderId: '484006019055',
    projectId: 'activity16-93cc8',
    authDomain: 'activity16-93cc8.firebaseapp.com',
    storageBucket: 'activity16-93cc8.firebasestorage.app',
    measurementId: 'G-C0YSWEPT5V',
  );
}
